### ISSUE TITLE
how to build and run this?

### ISSUE THREAD

**Issue by koem** [Marthym/jtomtom#1]
when I do mvn package I get an error "error: annotations are not supported in -source 1.3". When I add this to the pom.xml, it compiles:

```
    <build>   
    <pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>                                                             
            <artifactId>maven-compiler-plugin</artifactId>                                                          
            <version>3.0</version>          
            <configuration>
              <source>1.5</source>          
              <target>1.5</target>          
            </configuration>
          </plugin>
        </plugins>
    </pluginManagement>
    </build>
```

but now I can't run it:

```
koem@lenny:~/jtomtom:develop> java -jar ./jtomtom/target/jtomtom-1.0-SNAPSHOT.jar
kein Hauptmanifestattribut, in ./jtomtom/target/jtomtom-1.0-SNAPSHOT.jar
koem@lenny:~/jtomtom:develop> java -jar ./jcablib/target/jcablib-1.0-SNAPSHOT.jar
kein Hauptmanifestattribut, in ./jcablib/target/jcablib-1.0-SNAPSHOT.jar
```

**Comment by koem** [comment]
I was on the "develop" branch. When in master it runs from eclipse

**Comment by Marthym** [comment]
Hi,

I added the source and target in the pom to avoid the compilation problem. Thanks for that.

To run, after `mvn clean install` go into jtomtom-assembly, extract the tar.gz file in a dedicated directory and run jtomtom.sh with your GPS connected.

Keep in mind I haven't maintain this appli since many years. So it's possible your GPS was not supported.

Regards
Frédéric
